### ISSUE TITLE
How to run this on vercel

### ISSUE THREAD

**Issue by 0x-maker** [AugmentMo/NewsStack#1]
Is there any way to self host a version of Newsstack on vercel and call mongodb remotely? Or do u have to run it as a monolith all services on 1 machine?

**Comment by AugmentMo** [comment]
At the moment it is meant to run as monolith. Using vercel might be a good idea, however I do not have experience with it it this far. You are welcome to look into that. Surely it is possible and you can access mongodb remotely if you want. Happy to help in case you have more questions on how to run it locally.

**Comment by 0x-maker** [comment]
I was just wondering because the process of spinning up a Nginx instance and setting up all the certbot vars are monotonous. I cant run it locally without having ssl cert setup and vercel usually takes care of that. I know how to spin it up on ubuntu but im on windows and it didn't run. 

Is there a .env file maybe? 

how can I run it without ssl? I don't need user auth I just need to self host a instance for myself

**Comment by AugmentMo** [comment]
There is a .env file with access tokens etc. 
I will push a new version later that you can run immediately without using auth0/ssl/.. 
And also provide a description how to optionally configure the .env file to make it more accessible.

**Comment by AugmentMo** [comment]
Okay it should work now. I did it in a quick and dirty way. (Sorry for that, I have limited time but am happy if someone wants to use the project.)


It will now by default not use Auth0, ssl etc. and set up a http server.
However, if you define the right environment variables it will still try use ssl, Auth0, mixpanel ..
If you want a cleaner version without any ssl, auth0 code, you are welcome to remove the corresponding code. It should be easy to identify what to remove.

Please try following the steps in the updated readme and let me know if it works. 

You are welcome to contribute to this repository directly too.

Have fun & Cheers
Mo
